### ISSUE TITLE
Only Daily water usage works for Phyn Smart Water Assistant

### ISSUE THREAD

**Issue by kasik96** [MizterB/homeassistant-phyn#13]
Hi. I have Phyn Smart Water Assistant configured, and only Daily water usage works.

![image](https://github.com/MizterB/homeassistant-phyn/assets/7235992/9ded2452-e8dd-44ec-aba1-4f12594a9f9e)

All the others are grey, I think it should show for Hot and Cold separately. Is this even supported? 

If you can show me how I can debug this, I would be happy to help with coding :)

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:367
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 12:44:47 PM (2 occurrences)
Last logged: 7:19:52 PM
Error while setting up phyn platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 475, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/phyn/sensor.py", line 89, in native_value
    if self._device.current_flow_rate is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/phyn/device.py", line 86, in current_flow_rate
    return self._device_state["flow"]["mean"]
           ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'flow'`

**Comment by kasik96** [comment]
Update, the problem is that Phyn Smart Water Assistant have temperature1 and temperature2, then pressure1 and pressure2. I will create a pull request.

sov_status, water_consumption and flow is not availible

**Comment by kasik96** [comment]
Pull Request: https://github.com/MizterB/homeassistant-phyn/pull/14

Thanks :)

@MizterB
