### ISSUE TITLE
Phyn Integration Stopped working.  Tried delete/re-install, but failing

### ISSUE THREAD

**Issue by bh56** [MizterB/homeassistant-phyn#18]
I've had the Phyn HASS integration working for about a year.  I noticed the other day it was erroring out.  I deleted it and tried to re-install it, but I get an error.

Has something changed on Phyn's side causing this error/issue?

![image](https://github.com/MizterB/homeassistant-phyn/assets/9595141/a9ca1b3e-d50e-4971-8fbd-a372a8bca059)

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: December 14, 2023 at 7:11:17 PM (3 occurrences)
Last logged: 12:44:25 PM

Error setting up entry My House for phyn
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/phyn/__init__.py", line 28, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api(
                                                         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiophyn/api.py", line 140, in async_get_api
    await api.async_authenticate()
  File "/usr/local/lib/python3.11/site-packages/aiophyn/api.py", line 104, in async_authenticate
    auth_response = await asyncio.wrap_future(future)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiophyn/api.py", line 114, in _authenticate
    client = boto3.client("cognito-idp", region_name=COGNITO_REGION)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/boto3/__init__.py", line 92, in client
    """
        
  File "/usr/local/lib/python3.11/site-packages/boto3/session.py", line 299, in client
    :type use_ssl: boolean
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/session.py", line 971, in create_client
    self._session = session
                    ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/session.py", line 1042, in _resolve_defaults_mode
    env_var_names = None
                         
  File "/usr/local/lib/python3.11/site-packages/botocore/session.py", line 818, in _get_internal_component
    'response_parser_factory')
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/session.py", line 1140, in get_component
  File "/usr/local/lib/python3.11/site-packages/botocore/session.py", line 216, in create_default_config_resolver
    try:
         
  File "/usr/local/lib/python3.11/site-packages/botocore/loaders.py", line 471, in load_data
  File "/usr/local/lib/python3.11/site-packages/botocore/loaders.py", line 142, in _wrapper
  File "/usr/local/lib/python3.11/site-packages/botocore/loaders.py", line 453, in load_data_with_path
    :type extra_models: iterable of dict
botocore.exceptions.DataNotFoundError: Unable to load data for: sdk-default-configuration

**Comment by Hedda** [comment]
FYI, it looks like [jordanruthe](https://github.com/jordanruthe) has the most active fork(s) so might want to submit bugs/requests/PRs there if wish to collaborate:

https://github.com/jordanruthe/homeassistant-phyn

https://github.com/jordanruthe/aiophyn

https://github.com/jordanruthe/aiophyn/commits/dev/

And perhaps post link to the issue (without logs) to this existing community discussion in the Home Assistant forum:

https://community.home-assistant.io/t/phyn-integration-water-leak-detector/316197
